### ISSUE TITLE
The hunt for old domains?

### ISSUE THREAD

**Issue by krystian3w** [niutech/html5test#18]
```yml
html5test.com
Expires On: 2024-03-08
Should lose protection on: 2024-04-07

html5te.st
Expires On: 2024-04-07
Should lose protection on: 2024-05-08
```

Unless they turn out to be terribly expensive or a second after expiration some script redeems them or the owner's credit card payments overtake us.
