### ISSUE TITLE
Have a way to only show missing features

### ISSUE THREAD

**Issue by cristim** [niutech/html5test#28]
Now that most of the features are supported by the main browsers, would be great to have an optional view that only shows what's missing for each category, maybe controlled by a "Show only missing features" button next to the "Compare to..." button.

**Comment by krystian3w** [comment]
Using CSS in browsers what have added `:has(+ *)` can be used:

```css
tbody:not(:has(th + td :is(.partial, .ballot))),
thead:not(:has(+ tbody th + td :is(.partial, .ballot))) {
    display: none !important;
}
```

In older ones, you probably have to wait for a solution in JS or use, for example, uBlock Origin and its procedural filtering. This does not yet filter the rows, but can be added.
